using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace VortexEditor.Claude
{
    /// <summary>
    /// The tool reference for the docs website's Claude Tools page (docs repository, <c>docs/content/claude-tools.md</c>),
    /// generated from the tool definitions so it never drifts: <c>Vortex.Editor --mcp-tools-md=&lt;file&gt;</c> writes it
    /// and exits.
    /// </summary>
    public static class ToolReference
    {
        public static string Markdown()
        {
            var sb = new StringBuilder();
            var all = ToolCatalog.All;
            sb.Append("# Claude Tools\n\n");
            sb.Append("<!-- generated by `Vortex.Editor --mcp-tools-md=<file>` — do not edit by hand -->\n\n");
            sb.Append("The ").Append(all.Count).Append(" tools the Vortex editor offers to Claude — over the MCP server (Claude Code / Claude Desktop, ")
              .Append("where they appear as `mcp__vortex__<name>`) and in the Claude sidebar. ")
              .Append("Setup: [Claude in the Editor](#/claude). Every call that changes the scene is **one undo step** named `Claude: …`; ")
              .Append("**read-only** tools never change anything.\n\n");
            foreach (var group in all.GroupBy(t => t.Category))
            {
                sb.Append("## ").Append(group.Key).Append("\n\n");
                foreach (var t in group)
                {
                    sb.Append("### `").Append(t.Name).Append("`");
                    if (t.ReadOnly) sb.Append(" · read-only");
                    else if (t.ManagesUndo) sb.Append(" · editor state");
                    if (t.OpenWorld) sb.Append(" · internet");
                    sb.Append("\n\n").Append(t.Description).Append("\n\n");
                    var rows = Parameters(t.InputSchema).ToList();
                    if (rows.Count == 0) { sb.Append("_No parameters._\n\n"); continue; }
                    sb.Append("| Parameter | Type | Description |\n|---|---|---|\n");
                    foreach (var (name, type, desc, required, def) in rows)
                    {
                        sb.Append("| `").Append(name).Append('`').Append(required ? " **(required)**" : "").Append(" | ").Append(type)
                          .Append(" | ").Append(Escape(Sentence(desc))).Append(def != null ? " Default: `" + def + "`." : "").Append(" |\n");
                    }
                    sb.Append('\n');
                }
            }
            return sb.ToString();
        }

        private static IEnumerable<(string name, string type, string desc, bool required, string def)> Parameters(JsonElement schema)
        {
            if (schema.ValueKind != JsonValueKind.Object || !schema.TryGetProperty("properties", out var props)) yield break;
            var required = new HashSet<string>();
            if (schema.TryGetProperty("required", out var req) && req.ValueKind == JsonValueKind.Array)
                foreach (var r in req.EnumerateArray()) required.Add(r.GetString());
            foreach (var p in props.EnumerateObject())
            {
                string desc = p.Value.TryGetProperty("description", out var d) ? d.GetString() : "";
                string def = p.Value.TryGetProperty("default", out var dv) && dv.ValueKind != JsonValueKind.Null ? dv.GetRawText() : null;
                yield return (p.Name, TypeOf(p.Value), desc, required.Contains(p.Name), def);
            }
        }

        private static string TypeOf(JsonElement s)
        {
            if (!s.TryGetProperty("type", out var t)) return "any JSON";
            string Name(JsonElement x) => x.GetString() switch
            {
                "array" => s.TryGetProperty("items", out var it) && it.TryGetProperty("type", out var itt) ? (itt.ValueKind == JsonValueKind.String ? itt.GetString() : "value") + "[]" : "array",
                var other => other,
            };
            if (t.ValueKind == JsonValueKind.String) return Name(t);
            if (t.ValueKind == JsonValueKind.Array) return string.Join(" \\| ", t.EnumerateArray().Where(x => x.GetString() != "null").Select(Name));
            return "any JSON";
        }

        private static string Sentence(string s) => string.IsNullOrEmpty(s) || ".!?)".IndexOf(s[s.Length - 1]) >= 0 ? s : s + ".";

        private static string Escape(string s) => (s ?? "").Replace("|", "\\|").Replace("\n", " ");
    }
}
