#pragma once

#include "../../Common/CommonHeaders.h"
#include "../Geometry/IMeshGenerator.h"
#include <d3d12.h>
#include <wrl/client.h>
#include <string>

namespace vortex::graphics
{
	using Microsoft::WRL::ComPtr;

	/// <summary>
	/// GPU-resident mesh resource.
	/// Contains vertex and index buffers.
	/// </summary>
	class Mesh
	{
	public:
		Mesh() = default;
		~Mesh() = default;

		// Non-copyable
		Mesh(const Mesh&) = delete;
		Mesh& operator=(const Mesh&) = delete;

		// Movable
		Mesh(Mesh&& other) noexcept;
		Mesh& operator=(Mesh&& other) noexcept;

		/// <summary>
		/// Create mesh from MeshData (generated by IMeshGenerator).
		/// </summary>
		bool create(ID3D12Device* device, const MeshData& data);

		/// <summary>
		/// Create mesh from raw vertex/index data.
		/// </summary>
		bool create_from_vertices(ID3D12Device* device, const void* vertices, u32 vertex_count, u32 vertex_stride,
								  const u32* indices, u32 index_count);

		/// <summary>
		/// Create mesh from a generator.
		/// </summary>
		bool create_from_generator(ID3D12Device* device, const IMeshGenerator& generator);

		void destroy();

		const D3D12_VERTEX_BUFFER_VIEW& vertex_buffer_view() const { return m_vb_view; }
		const D3D12_INDEX_BUFFER_VIEW& index_buffer_view() const { return m_ib_view; }

		u32 index_count() const { return m_index_count; }
		u32 vertex_count() const { return m_vertex_count; }
		bool has_indices() const { return m_index_count > 0; }
		bool is_valid() const { return m_vertex_buffer != nullptr; }

		const std::string& name() const { return m_name; }
		void set_name(const std::string& name) { m_name = name; }

	private:
		ComPtr<ID3D12Resource> m_vertex_buffer;
		ComPtr<ID3D12Resource> m_index_buffer;
		D3D12_VERTEX_BUFFER_VIEW m_vb_view{};
		D3D12_INDEX_BUFFER_VIEW m_ib_view{};
		u32 m_vertex_count{ 0 };
		u32 m_index_count{ 0 };
		std::string m_name;
	};
}
